name: CI

on:
  push:
    branches: [ "GabrielPruebasUnitarias" ]
  pull_request:
    branches: [ "GabrielPruebasUnitarias" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Install Qt dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libegl1 \
          libgl1 \
          libglu1-mesa \
          libxcb-xinerama0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:src
        pytest tests
